### ISSUE TITLE
Help (SUPPORT) Displaying speaker labels

### ISSUE THREAD

**Issue by prokulit06** [watson-developer-cloud/android-sdk#73] opened 2019-02-25 08:39 UTC
Help how can i display speaker labels because when i trying to display speaker labels it is not consistent

  private class MicrophoneRecognizeDelegate extends BaseRecognizeCallback {

        @Override
        public void onTranscription(SpeechRecognitionResults speechResults) {
            System.out.println(speechResults);
            //this to enable Speaker Diarization
            SpeakerLabelsDiarization.RecoTokens recoTokens = new SpeakerLabelsDiarization.RecoTokens();
            if(speechResults.getSpeakerLabels() !=null)
            {
                recoTokens.add(speechResults);
                String speaks = "Speaker" + speechResults.getSpeakerLabels().get(0).getSpeaker().toString();
                showMicText(speaks);
            }if(speechResults.getResults() != null &&  !speechResults.getResults().isEmpty()) {
                recoTokens.add(speechResults);
                String text =  speechResults.getResults().get(0).getAlternatives().get(0).getTranscript();
                showMicText1(text);
            }

        }
please help me in the demo is so accurate but mine is not how can i do that i do my best please help me about this

**Comment by prokulit06** [comment] 2019-02-25 10:12
please help me sir :( please

**Comment by lpatino10** [comment] 2019-02-25 12:06
Duplicate of https://github.com/watson-developer-cloud/android-sdk/issues/72

**Closed by lpatino10** 2019-02-25 12:06 UTC
